// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqGyhUdcJJ1FgMkXJ31PKDns-BytyHM78',
    appId: '1:351321064728:web:7f8f0c86827724e7808a6d',
    messagingSenderId: '351321064728',
    projectId: 'wheels-6348c',
    authDomain: 'wheels-6348c.firebaseapp.com',
    storageBucket: 'wheels-6348c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0sp0Rjn61mQLokpI7yfsJa6C_WSdayTI',
    appId: '1:351321064728:android:8b7f26b3a2fc8e29808a6d',
    messagingSenderId: '351321064728',
    projectId: 'wheels-6348c',
    storageBucket: 'wheels-6348c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsfzIJMmZkOuP1Yk8Ec-QY_MaaG9APfsY',
    appId: '1:351321064728:ios:6b010f47a9d65f3c808a6d',
    messagingSenderId: '351321064728',
    projectId: 'wheels-6348c',
    storageBucket: 'wheels-6348c.appspot.com',
    iosClientId: '351321064728-1j5dcql81iesa2bd6qsfc2gddo5759fh.apps.googleusercontent.com',
    iosBundleId: 'co.edu.javeriana.vallesilicona.wheelspuj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsfzIJMmZkOuP1Yk8Ec-QY_MaaG9APfsY',
    appId: '1:351321064728:ios:6b010f47a9d65f3c808a6d',
    messagingSenderId: '351321064728',
    projectId: 'wheels-6348c',
    storageBucket: 'wheels-6348c.appspot.com',
    iosClientId: '351321064728-1j5dcql81iesa2bd6qsfc2gddo5759fh.apps.googleusercontent.com',
    iosBundleId: 'co.edu.javeriana.vallesilicona.wheelspuj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqGyhUdcJJ1FgMkXJ31PKDns-BytyHM78',
    appId: '1:351321064728:web:78865540544b6561808a6d',
    messagingSenderId: '351321064728',
    projectId: 'wheels-6348c',
    authDomain: 'wheels-6348c.firebaseapp.com',
    storageBucket: 'wheels-6348c.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAqGyhUdcJJ1FgMkXJ31PKDns-BytyHM78',
    appId: '1:351321064728:web:30a3ed375e733817808a6d',
    messagingSenderId: '351321064728',
    projectId: 'wheels-6348c',
    authDomain: 'wheels-6348c.firebaseapp.com',
    storageBucket: 'wheels-6348c.appspot.com',
  );
}
